### ISSUE TITLE
Problems in fitDTU function and usage in SingleCellExperiment class

### ISSUE THREAD

**Issue by mcortes-lopez** [statOmics/satuRn#25] opened 2023-02-10 22:17 UTC
Hi, 
I was trying to run satuRn in my sc data. I created a SingleCellExperiment object with the matrix of isoform counts as follows: 

```{r}
library(data.table)
library(DelayedArray)
library(tidyverse)
library(scuttle)


results_path <- "path/to/files"
count_mtxs <- list.files(results_path, pattern = "*transcript_grouped_counts.tsv", recursive = T, full.names = T)

# Read file and create a DelayArray matrix to make it easy to work with
mut01 <- fread(count_mtxs[1], data.table = F)
mut01.mtx <- mut01[, -1]
rownames(mut01.mtx) <- srsf2_mut01[, 1]
mut01.mtx_da <- DelayedArray(seed = mut01.mtx)

# Import cell annotations to create the groups 
sample_id <- gsub(".transcript_grouped_counts.tsv", "", basename(count_mtxs[1]))
cell_bcs <- fread("barcodes_celltypes.tsv", data.table = F ) %>% 
  filter(sample == sample_id) %>% 
  mutate(barcode = gsub("\\-[0-9]", "", barcode)) %>% 
  dplyr::select(-sample)

cell_bcs$celltype <- make.names(cell_bcs$celltype)

# Convert tx matrix into a sc object using the DelayArray matrix
library(SingleCellExperiment)
# Quality control and removal of outliers 
sce <- SingleCellExperiment(assays = list(counts = srsf2_mut01.mtx_da))
sce <- scuttle::addPerFeatureQC(sce)
sce <- scuttle::addPerCellQC(sce)

keep.hi <- isOutlier(sce$sum, type = "higher", log = TRUE)
keep.low <- isOutlier(sce$sum, type = "lower", log = TRUE)

sce <- sce[, (!keep.hi) & (!keep.low)]

rownames(cell_bcs) <- cell_bcs$barcode

bcintx <- intersect(colnames(sce), rownames(cell_bcs))
sce <- sce[, bcintx]

# Add cluster information to sc object
colData(sce) <- cbind(colData(sce), DataFrame(cell_bcs[bcintx,]))


# Analysis with satuRn
library(satuRn)


metadata(sce)$formula <- ~ 0 + as.factor(colData(sce)$celltype)
group <- (as.factor(sce$celltype))
design <- model.matrix(~ 0 + group) # constructs design matrix
colnames(design) <- levels(as.factor(colData(sce)$celltype))

L <- limma::makeContrasts(Contrast1 = HSCS - Late.EP,
                          Contrast2 = HSCS - Early.EP, 
                          levels = design) # constructs contrast matrix

# Add gene symbols
genetx <- rtracklayer::import.gff("combined.extended_annotation_clean.gtf")
genetx <- genetx[genetx$type =="transcript", ]
genetx <- data.frame("tx_id" = genetx$transcript_id, 
           "gene_id" =genetx$gene_id) 

library(biomaRt)

mart <- useMart(biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl")
gene_symbols_tab <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"), 
                          filters = "ensembl_gene_id", 
                          values = unique(grep("ENS", genetx$gene_id,value = T)), mart = mart)
gene_symbols_tab <- gene_symbols_tab %>%
  group_by(ensembl_gene_id) %>% 
  summarise(across(hgnc_symbol, ~ paste(unique(.x[!is.na(.x)]), collapse = "|"))) %>% 
  ungroup()

genetx <- left_join(genetx, gene_symbols_tab, by = c("gene_id" = "ensembl_gene_id"))

# Add isoform information to the data 
colnames(genetx) <-c("isoform_id", "gene_id", "symbol") 
rownames(genetx) <- genetx$isoform_id

rowData(sce) <- cbind(rowData(sce), DataFrame(genetx[rownames(rowData(sce)),]))


txInfo <- genetx[genetx$isoform_id %in% rownames(sce), ]
txInfo <- subset(genetx, 
                 duplicated(gene_id) | duplicated(gene_id, fromLast = TRUE))

sce <- sce[which(
  rownames(sce) %in% txInfo$isoform_id), ]



sce2 <- satuRn::fitDTU(sce,  formula =  ~0+group, parallel = FALSE,
                      BPPARAM = BiocParallel::bpparam(),
                      verbose = TRUE)
```

Then the error that I have is: 
`
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector
Error in names(models_gene) <- rownames(mat) : 
  invalid to use names()<- on an S4 object of class 'StatModel'`

I think it has something to do with empty values when calculating the statistics but I am not totally sure. Also, does satuRn works with SingleCellExperiments? I saw the tutorials from the paper but they seem quite outdated, it would be great if you could include an example in the vignettes.

**Comment by jgilis** [comment] 2023-02-11 07:55
Hi @mcortes-lopez,

`satuRn` can work with `SingleCellExperiment` objects. In the bioconductor vignette, we run `satuRn` on a `SummarizedExperiment` object, which have a very similar backbone structure  (SingleCellExperiment inherits from SummarizedExperiment).

I indeed think the error comes from either passing counts with NA's (e.g. https://stackoverflow.com/questions/35594236/logistic-regression-error-in-r), or counts with so many zeros the GLM can't be fitted.  I don't see you performing any feature-level filtering. Could you try that, either elaborately using something like the `filterByExpr` function of `edgeR`, or leniently by doing something like `sce <- sce[rowSums(assay(sce) > 0) > x,]`, with `n` an integer of how many cells at least need to have an expression higher than `x` (choose low value) for the feature to be retained. Also, can you check your sce object for NA values, i.e. in your count matrix and in your group variable?

If the issue persist, could you send me your `sessionInfo()`, so I can reproduce the R environment you are using and try to reproduce the error.

Best regards,

Jeroen

**Comment by mcortes-lopez** [comment] 2023-02-13 19:21
Hi @jgilis 

I did the read filter and then I had the same issue. Looking into the `fitDTU` function I realized that my SCE object had some genes with a single transcript, so the result of the fitting was NA but when the object was returned from the `fitQuasiLogistic` function, the next step was to unlist it and giving it a name, which caused the error. Maybe it might be good to add an option to just skip the lonely transcripts after the calculation of the fitting, or make it more obvious on the documentation that this is a quality control that has to be done before running the `fitDTU` function.

**Comment by jgilis** [comment] 2023-02-13 20:12
Hi @mcortes-lopez,

Happy to hear it is working now. I previously noted this issue, and should have resolved it in satuRn version 1.7.1. Could you confirm that you are running a version older that 1.7.1?

**Comment by mcortes-lopez** [comment] 2023-02-13 20:15
Hi @jgilis, 
I have: 
 satuRn               * 1.7.1     2023-02-13 [1] Github (statOmics/satuRn@94188ec)

**Comment by jgilis** [comment] 2023-02-13 20:37
Alright, that means my bug fix doesn't actually seem to fix the bug. I will check in  to it asap.
Thanks for spotting this!

**Comment by jgilis** [comment] 2023-02-14 08:25
Hi @mcortes-lopez, 

I have now updated to satuRn 1.7.2, which now should handle the "lonely transcripts" automatically. This should resolve the error `"Error in names(models_gene) <- rownames(mat) :  invalid to use names()<- on an S4 object of class 'StatModel'"`. 

For the sake of completeness, the other errors `"Error in family$linkfun(mustart) :  Argument mu must be a nonempty numeric vector"` indicate that the underlying GLM could not be fitted, which is usually due to very low counts. However, satuRn handles such features correctly by assigning them a class "fit-error" and setting their results to NA internally. I nevertheless wanted to not silence that error, because it can be useful to the user to know there are sparse features still in the data. I should, however, inform the user on this somewhere (todo).

I now also specifically mention in the vignette that satuRn can also use SingleCellExperiments and RangedSummarizedExperiments as input (thanks again for catching that). I will also update our website (https://statomics.github.io/satuRn/articles/Vignette.html) very soon.

Best regards,

Jeroen

**Comment by mcortes-lopez** [comment] 2023-02-17 20:32
Thanks a lot @jgilis ! I will test it in the following days. 
I have an additional question, what is your recommendation to analyze Single cell experiments with multiple samples from a certain condition? Do you recommend assay DTU per sample or rather through a complex design like the included in the paper?
Also, is there a way to obtain the results of plot DTU without making the plot? I would like to make other type of visualizations but I would need the isoform ratios. 
Best, 
Mariela

**Comment by jgilis** [comment] 2023-02-24 10:09
Hi @mcortes-lopez,

For your first question: yes, `satuRn` can accommodate complex experimental (cross-sectional) designs using the model formula. I would recommend doing it that way and model the data jointly if possible.

That said, with multi-patient data, there is an additional challenge. Essentially what happens is that cells of the same patient are more alike compared to cells of other patients. As such, cells of the same patient can be considered pseudo-replicates (non-independent), which violates the independence assumption that most methods use (satuRn, edgeR, DESeq2, ...). Ignoring this will lead to overly liberal results. Recently, many people have started looking at this problem. There are two categories of solutions; model these within-patient dependencies (e.g. using mixed models https://www.nature.com/articles/s42003-021-02146-6 or generalized estimation equations) or pseudo-bulk your data, as proposed by https://www.nature.com/articles/s41467-020-19894-4 and https://www.nature.com/articles/s41467-021-25960-2. Pseudo-bulking means aggregating counts per patient-cell type combination, so you don't lose cell type resolution, but alleviates the pseudo-replication issue. I recommend pseudo-bulking your data (using the `muscat` package or the `aggregateAcrossCells` of the `scuttle` package) first, and then do your DGE or DTU analyses.

---

For making the plots: you can look at my source code of both the wrapper function and the worker function with,

```
satuRn:::plotDTU
satuRn:::plotDTU_internal
```

Essentially what I do is I compute usages, make violin plots of them, and add individual points where the size of the points represents the gene (not transcript) count, as this determines how influential an observation will be. The reason my code is quite complex is because I additionally want to allow the user to automatically display the group-level average usage as estimated by the `satuRn` model; if you omit that, or make it non-automatic, then the plot can be made quite easily.

Best regards,

Jeroen

**Comment by jgilis** [comment] 2023-03-03 09:41
I will close this issue because the bug should be fixed. Feel free to continue the discussion below, or reopen the issue if you still experience a problem.

Thanks for contributing the issue!

**Closed as completed by jgilis** 2023-03-03 09:41 UTC
Labels: bug
