### ISSUE TITLE
[BUG] Using contrasts with covariates

### ISSUE THREAD

**Issue by jackhump** [statOmics/satuRn#10] opened 2021-03-18 22:36 UTC
Hello again Jeroen!

I got the vignette example and I'd like to try running satuRn on my dataset. I have bulk RNA-seq samples from microglial cells isolated from 4 different brain regions and I want to perform pairwise DTU between each pair.  I have 255 samples in total so I was never going to be able to run DEXSeq - satuRN is really a wonderful improvement for the field!

I set up my contrast matrix using limma::makeContrasts to create the 6 pairwise comparisons.  fitDTU took around 2 minutes to test 60,000 transcripts and testDTU took no time at all. 
For the contrast I know should have the most signal I find 19,847 transcripts with DTU at regular FDR < 0.05 but only 26 at empirical FDR < 0.05, is that to be expected?

I know from our gene expression work that there are several important batch effects in RNA quality, plus I want to adjust for donor age and sex. I therefore ran fitDTU again with a formula containing the covariates.  Then when I ran testDTU I get the following error:

```
Error in contrast %*% coef : non-conformable arguments
```

I tracked this down to the getCoef() subfunction, which is attempting matrix multiplication between `contrast`, which has 4 elements (the 4 regions) and `coef`, which has 13 elements, the 4 regions plus my 9 covariates, so it fails.

Am I inputting the covariates correctly here? Any advice or guidance would be much appreciated.

best,

Jack

**Comment by jgilis** [comment] 2021-03-19 13:19
Hi Jack,

First of, 60K transcripts seems quite a lot to me even with bulk data. It could be fine, just make sure to sufficiently filter the data prior to analysis, e.g. using the function `filterByExp` from edgeR or `dmFilter` from DRIMseq.

Second, I would advise you to have a look at the resulting p-value distributions, both of the "raw" and "empirical" p-values. Ideally, they should either be uniformly distributed over the entire [0,1] interval (no DE signal) or uniformly distributed over say the [0.05,1] interval with a peak on say p-values <0.05 (indicative of DE signal). To our findings, the raw p-values are often strongly skewed towards small p-values for most methods; working under an empirical null should help alleviating this issue.

Finally, it does indeed sound that the contrasts you are provided are not correctly specified. Inputting these correctly really is not trivial, however, crucial for final interpretation. We are using the same strategy for specifying contrasts as `limma` and `edgeR`. Relevant information for specifying contrasts is available by their respective authors, e.g. https://support.bioconductor.org/p/104685/ (specific) and chapter 3 of https://www.bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf (general).

As your question is very relevant for everyone using `satuRn`, I below show a minimal example of how to specify a design like yours.

Best,

Jeroen

**Comment by jgilis** [comment] 2021-03-19 13:32
(Relatively long script so maybe not ideally suited for a Github issue, but will do for now)

## Generate minimal example data

```{r}
set.seed(85133)

# Generate the transcript-level counts
tx1 <- rpois(200,2) # foo expression of transcript 1 of gene A
tx2 <- rpois(200,4) # foo expression of transcript 2 of gene A
tx3 <- rpois(200,6) # foo expression of transcript 3 of gene A
counts <- rbind(tx1, tx2, tx3)
rownames(counts) <- c("tx1", "tx2", "tx3")

# Generate the rowData
txInfo <- as.data.frame(matrix(data = NA, nrow = 3, ncol = 2))
colnames(txInfo) <- c("isoform_id", "gene_id")
txInfo$isoform_id <- c("tx1", "tx2", "tx3")
txInfo$gene_id <- rep("geneA", times=3)

# Generate the colData
colData <- as.data.frame(matrix(data = NA, nrow = 200, ncol = 3))
colnames(colData) <- c("group", "sex", "age")
colData$group <- as.factor(rep(c("A","B","C","D"), each=50)) # your 4 different group labels for 200 samples
colData$sex <- as.factor(rep(rep(c("Male", "Female"),each=25), times=4)) # for each group, 25 males and 25 females
colData$age <- rnorm(n=200, mean=50, sd=10) # taken as a quantitative variable, could also be an age category

# Put all elements in a SummarizedExperiment object
sumExp <- SummarizedExperiment::SummarizedExperiment(
    assays = list(counts = counts),
    colData = colData,
    rowData = txInfo
)
```

## Fit DTU models

```{r}
metadata(sumExp)$formula <- ~ 0 + sumExp$group + sumExp$sex + sumExp$age
# Note: there are many equivalent ways for specifying one and the same model.
# What works best for me is to always start with "0 + covariate of interest",
# so that the first column in the design matrix is the first group of the
# covariate of interest

sumExp <- satuRn::fitDTU(
    object = sumExp,
    formula = ~ 0 + sumExp$group + sumExp$sex + sumExp$age,
    parallel = FALSE,
    BPPARAM = BiocParallel::bpparam(),
    verbose = TRUE
)

rowData(sumExp)[["fitDTUModels"]][[1]]@params$coefficients
```

## Set up contrasts

```{r}
design <- model.matrix(~ 0 + sumExp$group + sumExp$sex + sumExp$age)
# To construct the contrast matrix, it is required to use the same formula
# as in the design matrix to ensure matching dimensionality. 
# The `makeContrasts` function by limma can then be used to specify which
# parameters in the models you are interested in for testing.
colnames(design) <- c("groupA",
                      "groupB",
                      "groupC",
                      "groupD",
                      "sexMale",
                      "Age") # just making them clearer

L <- limma::makeContrasts(Contrast1 = groupA - groupB,
                          Contrast2 = groupA - groupC,
                          Contrast3 = groupA - groupD,
                          Contrast4 = groupB - groupC,
                          Contrast5 = groupB - groupD,
                          Contrast6 = groupC - groupD,
                          levels = design)
L # Each of the 6 colums specifies a contrast of interest

> L
        contrast1 contrast2 contrast3 contrast4 contrast5 contrast6
groupa          1         1         1         0         0         0
groupb         -1         0         0         1         1         0
groupc          0        -1         0        -1         0         1
groupd          0         0        -1         0        -1        -1
sexMale         0         0         0         0         0         0
age             0         0         0         0         0         0
```


## Test for DTU

At this point, you'd want to run the `testDTU` function. However, given there
are only 3 transcripts in the data, the function will throw an error, as the
procedure we adopt cannot construct an empirical null distribution when the 
number of features in the data is that small.

For demonstration purposes, I therefore opened up the `testDTU` function and 
commented out the part of the funcion that requires the empirical null.

```{r}
object = sumExp
contrasts = L
plot = FALSE
sort = FALSE

models <- rowData(object)[["fitDTUModels"]]

for (i in seq_len(ncol(contrasts))) {
    
    estimates <- vapply(X = models, FUN = satuRn:::getEstimates, contrast = contrasts[, 
        i], FUN.VALUE = numeric(1))
    
    se <- sqrt(vapply(X = models, FUN = satuRn:::varContrast, contrast = contrasts[, 
        i], FUN.VALUE = numeric(1)))
    
    df <- vapply(X = models, FUN = satuRn:::getDfPosterior, FUN.VALUE = numeric(1))
    df[!(vapply(df, length, numeric(1)))] <- NA
    df <- unlist(df)
    
    t <- estimates/se
    
    pval <- pt(-abs(t), df) * 2

    # regular_FDR <- p.adjust(pval, method = "BH")
    # empirical <- satuRn:::p.adjust_empirical(pval, t, plot = plot)
    # empirical_pval <- empirical$pval
    # empirical_FDR <- empirical$FDR
    # 
    # result_contrast <- data.frame(estimates, se, df, t, pval, 
    #     regular_FDR, empirical_pval, empirical_FDR)
    # 
    # if (sort == TRUE) {
    #     result_contrast <- result_contrast[order(result_contrast$empirical_pval),]
    # }
    # 
    # rowData(object)[[paste0("fitDTUResult_", colnames(contrasts)[i])]] <- result_contrast
    
    print(pval)
}
```

      tx1       tx2       tx3 
0.9057280 0.7580482 0.9133707 
      tx1       tx2       tx3 
0.5336557 0.8165105 0.4713603 
      tx1       tx2       tx3 
0.7668206 0.5390515 0.3867082 
      tx1       tx2       tx3 
0.4627314 0.9367667 0.5455086 
      tx1       tx2       tx3 
0.8616806 0.3628032 0.3368796 
      tx1       tx2       tx3 
0.3603121 0.3984459 0.1143296 

## Alternative parameterization

As said, there are multiple ways of correctly specifying equivalent models.
Here is one alternative

```{r}
sumExp <- satuRn::fitDTU(
    object = sumExp,
    formula = ~ 0 + sumExp$sex + sumExp$age + sumExp$group, # group at end
    parallel = FALSE,
    BPPARAM = BiocParallel::bpparam(),
    verbose = TRUE
)

design <- model.matrix(~ 0 + sumExp$sex + sumExp$age + sumExp$group)
# To construct the contrast matrix, it is required to use the same formula
# as in the design matrix to ensure matching dimensionality. 
# The `makeContrasts` function by limma can then be used to specify which
# parameters in the models you are interested in for testing.
colnames(design) <- c("sexFemale",
                      "sexMale",
                      "age",
                      "groupB",
                      "groupC",
                      "groupD") # just making them clearer

# when only 1 group specified as contrast, it has the interpretation of a coefficient
L <- limma::makeContrasts(Contrast1 = groupB, 
                          Contrast2 = groupC,
                          Contrast3 = groupD,
                          Contrast4 = groupB - groupC,
                          Contrast5 = groupB - groupD,
                          Contrast6 = groupC - groupD,
                          levels = design)

> L
```

```{r}
object = sumExp
contrasts = L
plot = FALSE
sort = FALSE

models <- rowData(object)[["fitDTUModels"]]
for (i in seq_len(ncol(contrasts))) {
    
    estimates <- vapply(X = models, FUN = satuRn:::getEstimates, contrast = contrasts[, 
        i], FUN.VALUE = numeric(1))
    
    se <- sqrt(vapply(X = models, FUN = satuRn:::varContrast, contrast = contrasts[, 
        i], FUN.VALUE = numeric(1)))
    
    df <- vapply(X = models, FUN = satuRn:::getDfPosterior, FUN.VALUE = numeric(1))
    df[!(vapply(df, length, numeric(1)))] <- NA
    df <- unlist(df)
    
    t <- estimates/se
    
    pval <- pt(-abs(t), df) * 2
    print(pval)
}
```

      tx1       tx2       tx3 
0.9057280 0.7580482 0.9133707 
      tx1       tx2       tx3 
0.5336557 0.8165105 0.4713603 
      tx1       tx2       tx3 
0.7668206 0.5390515 0.3867082 
      tx1       tx2       tx3 
0.4627314 0.9367667 0.5455086 
      tx1       tx2       tx3 
0.8616806 0.3628032 0.3368796 
      tx1       tx2       tx3 
0.3603121 0.3984459 0.1143296 

Equivalent models -> excatly the same results

**Comment by jgilis** [comment] 2021-04-01 06:41
Dear Jack,

I will close the issue. If there still would be an issue here, feel free to have me reopen it.

Good luck with your analyses,

Jeroen

**Closed as completed by jgilis** 2021-04-01 06:41 UTC

**Comment by jackhump** [comment] 2021-04-01 16:47
Apologies for the delay. Yes, your code worked beautifully! Thanks for your help.  

I'm looking forward to using satuRn more and more in my work!

One final question: how best to explain the "estimates" column of the  DTU results? Is this analogous to a log2 fold change for differential splicing?   Would an estimate of +1 would be a doubling of transcript usage for that transcript?

**Comment by jgilis** [comment] 2021-04-09 14:30
Happy to help and very glad to hear you found satuRn useful! :)

The interpretation of the estimates is indeed analogous to the log2 fold change in a classical gene-level DE analysis. More specifically, since `satuRn` can be seen as a tweaked logistic regression, the estimates are log-odds ratios (log base e). In the most simple case, an estimate of +1 would mean that the odds of picking that transcript from the pool of transcripts within its corresponding gene is exp(1) = 2.72 times larger in condition B than in condition A.

That said, interpreting the estimates directly can become tricky when the experimental design is complex, as is the case in your dataset. Just as in a classical differential gene expression analysis, the estimates would refer to the parameter of interest (e.g. a treatment effect) after correction for e.g. age and batch.
